name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get ARM Binutils
      run: apt-get install -Y binutils-arm-none-eabi
    
    - name: Get Rust Source
      run: rustup component add rust-src
    
    - name: Build Examples
      run: cargo build --verbose --examples
